# action.yml
name: 'OpenAI Code Reviewer - Azure'
description: 'Greet someone and record the time'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  openai-api-key:  # id of input
    description: 'OpenAI API Key'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.openai-api-key }}
