name: Code Review
on:
  push:
permissions:
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: OpenAI Code Reviewer - Azure
      uses: alexjose/openai-code-review@v1-beta
